version: '3'

services:
  db:
    image: postgres
  django-app:
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./django:/usr/src/app
    
    command: python3 manage.py runserver 0.0.0.0:5000
    depends_on:
      - db
    # environment:
    #   - FLASK_RUN_HOST=0.0.0.0
    #   - FLASK_APP=app.py

  apache:
    image: httpd
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - "80:80"
    depends_on:
      - flask-app
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
